CREATE TABLE IF NOT EXISTS actions (
    id INTEGER PRIMARY KEY,
    action_name TEXT NOT NULL,
    processing INTEGER DEFAULT 0,
    processed INTEGER DEFAULT 0,
    added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS colors (
    id INTEGER PRIMARY KEY,
    value TEXT NOT NULL,
    added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    action_id INTEGER,
    FOREIGN KEY (action_id) REFERENCES actions(id)
);
